### ISSUE TITLE
CC sometimes gets stuck when swiping down too fast

### ISSUE THREAD

**Issue by Aransh** [ioscreatix/Maize#101]
https://vimeo.com/244184170
I thought it was  just a small bug at first, but I keep getting it and then I have to tap the home button to exit
EDIT: doesn't necessarily have something to do with soeed, I can now reproduce it about 4/5 times, I think it's something about where you release your finger
https://vimeo.com/244188118

**Comment by andrewwiik** [comment]
turn of "Use New Bounce" in HMX

**Comment by Aransh** [comment]
@andrewwiik Don't have it on, It was a flex patch. I turned it off and couldn't reproduce anymore, thanks 👌🏽
