### ISSUE TITLE
When scrolling the time in Music Module, it changes from 2:32 to 02:32 etc

### ISSUE THREAD

**Issue by soljd** [ioscreatix/Maize#110]
Screenshots: https://imgur.com/a/zs1Jb

iPhone SE
iOS 10.2

**Comment by andrewwiik** [comment]
I don't see the issue

**Comment by soljd** [comment]
Just small stuff, pointing out everything

**Comment by andrewwiik** [comment]
No I mean I don't get what the problem is in the screenshot, I don't know what you want me to fix with this issue

**Comment by soljd** [comment]
Oh, the second screenshot is when scrubbing the to switch the time in music. It's supposed to look like it does on the music app. 

https://imgur.com/a/lb2v2

**Comment by Aransh** [comment]
Yup, I'm also getting this

**Comment by andrewwiik** [comment]
This has been fixed
