### ISSUE TITLE
Continuous movement on the flashlight module isn't the same as the others

### ISSUE THREAD

**Issue by soljd** [ioscreatix/Maize#111]
In the other modules (brightness, volume), you could long press and immediatelly slide up from anywhere on the screen to change the values. In the flashlight module, your finger has to be exactly in the middle where the icon is for it to work.

**Comment by andrewwiik** [comment]
This behavior is on purpose, the flashlight level will only change when your finger is inside the flashlight, the behavior is the same on iOS 11
