### ISSUE TITLE
Flipswitch toggles with conformation bug

### ISSUE THREAD

**Issue by ibrahimqatar** [ioscreatix/Maize#117]
If you have a toggles such as the respring with the confirmation pop up option set to on, tapping on the toggle then canceling will have the icon set as enabled until a respring is done.

**Comment by 0j0k3r** [comment]
I experienced the same, but with my custom 'Polus' WhatsApp toggle. I set that toggle to start it immediatly from my LockScreen, without prompting my Passcode. When I try to start WhatsApp from my custom Polus toggle with Maize enabled, that Passcode comfirmation screen pops up, when I try the same but with Maize disabled via iCleaner, I dont have that Passcode prompt, I can open WhatsApp from my LS, and when I press the home button, the device iss locked (really nice behaviour)

**Comment by andrewwiik** [comment]
@0j0k3r your issue is not related to the one he is talking about in any way

**Comment by andrewwiik** [comment]
Fixed the actual issue listed here

**Comment by 0j0k3r** [comment]
should I better do open a separate Issue, with that what I write above?
