### ISSUE TITLE
Music Module's Marquee not cropped if you browse songs while music isn't playing

### ISSUE THREAD

**Issue by Aransh** [ioscreatix/Maize#119]
![Image](https://i.imgur.com/9sGRxsy.jpg) as you can see in the screenshot, I paused my previously played song and started browsing what song to play next, any song with a Marquee long enough to be cropped was not cropped until I pressed play

**Comment by andrewwiik** [comment]
Fixed in 54183e7fca9043b31bae245a758244c9cf080362, will be in next release
