### ISSUE TITLE
Volume icon is hard to discern from background when invoking CC on a white page [6S, 10.2]

### ISSUE THREAD

**Issue by braedonrogers99** [ioscreatix/Maize#12]
Make sure volume level is above the volume level, and open a white page (like settings). Idk if that's a big enough issue. [6S, 10.2]

**Comment by andrewwiik** [comment]
I added a shadow though

**Comment by julianschiavo** [comment]
This also happens with the brightness icon (displaymodule). Would be nice if they could be inverted like all the other modules on light bgs!

**Comment by andrewwiik** [comment]
Pretty sure this issue has been resolved as of now so I am closing this
