### ISSUE TITLE
Lag when toggling brightness module

### ISSUE THREAD

**Issue by Inkhearted** [ioscreatix/Maize#124]
When using the brightness toggle, it's so laggy, unlike using the volume toggle that's very smooth.

**Comment by Aransh** [comment]
I experience the same thing, but only when low power mode is on

**Comment by Inkhearted** [comment]
Yeah, but it's not as smooth as the volume toggle.

**Comment by SilentOcean2017** [comment]
So weird I don't have that issue. Both of mine are smooth even in power mode. I'm on 10.1

**Comment by ianrod30** [comment]
Same problem. Low power mode or not there's times where it'll stutter hard and it's not as fluid as the volume toggle

**Comment by andrewwiik** [comment]
Fixed
