### ISSUE TITLE
I can see my airdrop toggle even before i expand the connectivity section.

### ISSUE THREAD

**Issue by zyan910** [ioscreatix/Maize#136]
![img_2721](https://user-images.githubusercontent.com/31066253/33239861-aedcf094-d2c4-11e7-9159-4855d9620851.PNG)

**Comment by zyan910** [comment]
Look at the connectivity toggle, i can see my Airdrop button right below

**Comment by andrewwiik** [comment]
Fixed

**Comment by Iknotum** [comment]
Will this be released on the next version? Now I don't see the changes in 1.0.5.
