### ISSUE TITLE
Safe mode after install

### ISSUE THREAD

**Issue by Arrow-Li** [ioscreatix/Maize#138]
iOS 10.0.1 iPhone 7

**Comment by andrewwiik** [comment]
Tweak List?

**Comment by Arrow-Li** [comment]
- AirDrop Flipswitch
- Alkaline
- Apex 2
- AFC2
- AppList
- DockShift
- DoNotAnnoy
- EmojiPort
- exKeyboard
- Filza
- Flex 3
- FlipControlCenter
- Kaze
- LockGlyphx
- Springtomize 4
- TypeStatus 2

**Comment by Arrow-Li** [comment]
Already know, not compatible with **AirDrop Flipswitch**

**Comment by andrewwiik** [comment]
Got it

**Comment by MRedaCraft** [comment]
Happed to me, just remove Flipcontrolcenter.
