### ISSUE TITLE
Flashlight flickering if triggered by Activator

### ISSUE THREAD

**Issue by legitcomputerwhisperer** [ioscreatix/Maize#139]
When the flashlight is triggered via Activator action the beam flickers/strobes while on. This issue only occurs when the flashlight module is included in your active Maize configuration. The flashlight works without flickering when triggered via Maize toggle. This issue resolves when the flashlight module is not included (disabled) in Maize.

Maize Version Tested: v1.0.4
Activator Version Installed: v1.9.13~beta1
Devices Tested: iPhone 6s Plus iOS 10.2, iPhone 5s iOS 10.2, iPhone 5s iOS 10.1.1
Logs/CrashReports: None generated

**Comment by andrewwiik** [comment]
Love the detail in this issue, will look into fixing

**Comment by maheshdj** [comment]
I experience same issue

**Comment by andrewwiik** [comment]
Fixed, will be in next version on BigBoss
