### ISSUE TITLE
Alternate layout for iPads

### ISSUE THREAD

**Issue by Iknotum** [ioscreatix/Maize#142]
Maize:
![img_1293](https://user-images.githubusercontent.com/22131016/33300153-21ce7b42-d3ef-11e7-962a-7e6fe505f425.PNG)
![img_1294](https://user-images.githubusercontent.com/22131016/33300154-21fd8888-d3ef-11e7-89b6-cb2ef59d663a.PNG)

My proposal:
With the intention of maintaining a similarity in the order of the icons and modules, I would split the grid in two sections and limit the number of columns in landscape per section to 5, so that in vertical orientation the two sections will form one of 10 columns.
![img_1295](https://user-images.githubusercontent.com/22131016/33300301-dac1a0fc-d3ef-11e7-86d7-e71e86271e57.PNG)
![img_1296](https://user-images.githubusercontent.com/22131016/33300303-daeed072-d3ef-11e7-9a20-cbe11aa1db3c.PNG)

**Comment by andrewwiik** [comment]
Violates Maize's design rules, will not implement, sorry
