### ISSUE TITLE
Animations & Long Press

### ISSUE THREAD

**Issue by Greg212** [ioscreatix/Maize#15]
iPhone SE, iOS 10.1.1, iPhone 6-Resolution (LittleBrother) and normal Resolution tested

The Animation of flashlight slider needs To be a bit smoother (expanded big slider). The transition is the Problem.. Volume Transition is ok, could be smoother, but not urgently.

Why does a Long Press on eg. Low Power Mode gives a 3D Touch animation..? Nothing here to expand.

I'm looking forward to final release :) will buy it for sure! CCXI is already Great but this One Tops it.

**Comment by andrewwiik** [comment]
In iOS 11 if something doesn't have 3D touch it still expands then shrinks first, what does "expanded big slider" mean? The latest preview smooths some things out and fixes some gesture things, I am closing this issue for now.

**Comment by Greg212** [comment]
Thanks for your response! 
I did not know that! Instead of complaining I should have compare it with ios 11 at first :) 
Well.. 'expanded big slider' means the big slider which appears if you long press on the flashlight toogle.

Thank you very mich (and I mean it).
