### ISSUE TITLE
Invoke Lag/Slowness 

### ISSUE THREAD

**Issue by ahanank** [ioscreatix/Maize#154]
There is a lag/slowness to when Maize is invoked in version 1.0.5 as compared to version 1.0.2-83. As far as the lag is concerned, 1.0.2-83 had no issues as it was instant. Below are the links for video comparisons: 
Version 1.0.5: https://streamable.com/nl932
Version 1.0.2-83: https://streamable.com/fucp0

**Comment by andrewwiik** [comment]
Put your device and iOS Version and if you want a tweak list, though the device and iOS Version are def needed

**Comment by ahanank** [comment]
iPhone 7 Plus, 10.1.1 on extra_recipe.

Tweak list did not change between those versions nor any updates ever since.

**Comment by andrewwiik** [comment]
Yes but maybe something new i introduced caused a tweak conflict so a tweak list would be awesome

**Comment by ahanank** [comment]
Oh, ok.
Here it is: https://pastebin.com/DZUu7CG6

**Comment by Faezan** [comment]
https://streamable.com/k871n

**Comment by Faezan** [comment]
I'm in iOS 10.2 iPhone 6+

**Comment by andrewwiik** [comment]
Hopefully this is fixed with the hours I spent on this today

**Comment by Faezan** [comment]
No on the latest version of Maize 1.0.5 it is not fixed
