### ISSUE TITLE
[Request/Enhancement] Compatibility with CCClockOpenToAlarm 8+

### ISSUE THREAD

**Issue by sween64** [ioscreatix/Maize#159]
This tweak causes the control centre clock shortcut to open to the alarm page instead of the timer page. Flip Control Center had a similar setting. Please make this an option or enable compatibility. Thank you.

**Comment by Aransh** [comment]
You can do that in Maize with Polus and Activator

**Comment by andrewwiik** [comment]
Agree with @Aransh until I write the actual timer module with the set timer thing which will allow alarms to be their own module
