### ISSUE TITLE
Tweak required travel on volume/brightness bars

### ISSUE THREAD

**Issue by crackout666** [ioscreatix/Maize#16]
The adjustment of the bars should require less travel. If not and the bar is located at the bottom of the CC, sliding down on the bar the fingertip leaves the active touch area before the level is at minimum.

**Comment by braedonrogers99** [comment]
I disagree haha. I like the 1:1 we have now

**Comment by andrewwiik** [comment]
I kinda agree with crackout a little here haha, i have had slight annoyances with my current calculations

**Comment by andrewwiik** [comment]
Tweaked
