### ISSUE TITLE
Safe mode immediately when trying to open control center - iPad

### ISSUE THREAD

**Issue by jakeajames** [ioscreatix/Maize#17]
Ok so I saw @ioscreatix on Twitter and they said it works on iPad + videos. I tried this (downloaded from ioscreatix repo) and all it does is safe mode. 

iPad Air 2 - iOS 10.2

**Comment by Quoll-io** [comment]
Please attach crash logs. Thanks :)

**Comment by jakeajames** [comment]
@LaughingQuoll Since I don't have CrashReporter there's no blame. Here: https://pastebin.com/raw/mhZha7JJ

I also removed binary images, since I have some private stuff in here. If you need CrashReporter crash or full crash log tell me

**Comment by andrewwiik** [comment]
The log pasted is absolutely useless

**Comment by jakeajames** [comment]
@andrewwiik Do I need to use CrashReporter or what? Thanks

**Comment by jakeajames** [comment]
@andrewwiik @LaughingQuoll CrashReporter log - https://pastebin.com/raw/mKfHV6xK

**Comment by andrewwiik** [comment]
Fixed, will be in next preview release later tonight
