### ISSUE TITLE
Long loading CC

### ISSUE THREAD

**Issue by Amcro** [ioscreatix/Maize#18]
It's not really a bug, but first swipe after respring takes some time to open CC. Same problem can be found on Horseshoe. I'm using iPhone SE on 10.2

**Comment by Quoll-io** [comment]
Hi,

This is needed because the CC has to load.

We are investigating a good place to put this but for now it will occur on the first pull up of the CC.

It shouldn't lag after that.

Thanks :)

**Comment by alexdiazz** [comment]
Works fine for me, opens in an instance

**Comment by andrewwiik** [comment]
Fixed, Maize now preloads the modules after  respring when the LS appears to alleviate this problem.
