### ISSUE TITLE
Not working on iPad Air 2 after 1.0.3 update....

### ISSUE THREAD

**Issue by zyan910** [ioscreatix/Maize#21]
It was working fine until I updated it to 1.0.3, where only the blur would pop up and the toggle and everything are not showing up.

**Comment by andrewwiik** [comment]
More explanation and a screenshot please

**Comment by zyan910** [comment]
![img_2253](https://user-images.githubusercontent.com/31066253/29430067-9b8dbb76-83b0-11e7-9949-4bcf79720557.PNG)
The blur is there, toggles aren't....

**Comment by andrewwiik** [comment]
Device and iOS Version?

**Comment by zyan910** [comment]
iPad Air 2, iOS 10.1

**Comment by andrewwiik** [comment]
Has this been fixed in the latest version?

**Comment by zyan910** [comment]
Not yet :/

**Comment by andrewwiik** [comment]
I think you may have a conflicting tweak

**Comment by zyan910** [comment]
I tried to install it after disabling every other tweak via iCleaner Pro, still same result

**Comment by zyan910** [comment]
Ok so I reinstalled and got it working but once i respringed, the blur was just there, no toggles

**Comment by zyan910** [comment]
Latest version fixed it, thx. It still has bugs in landscape mode
