### ISSUE TITLE
Flashlight blinking when changing modes in the Camera app, and stays on after exiting.

### ISSUE THREAD

**Issue by izzulaizad95** [ioscreatix/Maize#22]
In the camera app, swapping between modes causes the flashlight to blink on then turn off. After getting out of the camera app, the flashlight turns on, with or without it turned on before launching the camera app.

**Comment by andrewwiik** [comment]
Please state your device and iOS Version and I also was unable to reproduce this bug on my iPad Pro 9.7 inch on IOS 10.2

**Comment by izzulaizad95** [comment]
iPhone SE iOS 10.2
