### ISSUE TITLE
CC doesn't change orientation to landscape mode in lock screen camera. 

### ISSUE THREAD

**Issue by izzulaizad95** [ioscreatix/Maize#23]
In lock screen camera, the CC can't be swiped from the bottom when in landscape mode. This doesn't happen when the camera is launched from Springboard.

**Comment by andrewwiik** [comment]
Device and iOS Version?

**Comment by izzulaizad95** [comment]
iPhone SE iOS 10.2

**Comment by andrewwiik** [comment]
I can't reproduce this issue either on my IPad Pro on 9.7 inch

**Comment by izzulaizad95** [comment]
Could it be an issue with Polus compatibility?

**Comment by izzulaizad95** [comment]
Strange, now I don't have the issue anymore. Even with Polus on. I apologize. This applies to ny other issue regarding the flashlight too.
