### ISSUE TITLE
Battery life goes down the drain while installed/enabled with iCleaner [i6S, 10.2]

### ISSUE THREAD

**Issue by braedonrogers99** [ioscreatix/Maize#25]
I'm sure this is known, but just so you can check another thing off your list ;) [i6S, 10.2]

**Comment by andrewwiik** [comment]
Actually this isn't known and considering Maize code is only run when the CC is open I find this hard to believe

**Comment by braedonrogers99** [comment]
I actually notice this happening with ccxi as well. This may be because I can't toggle things like airplane mode and Bluetooth and such in the betas, or adjust brightness. Maybe I just need a new battery lol.
