### ISSUE TITLE
CC view takes up top left corner of screen only 

### ISSUE THREAD

**Issue by Tom-Knighton** [ioscreatix/Maize#26]
![img_0334](https://user-images.githubusercontent.com/29462246/29405368-98204380-8335-11e7-9f15-9dcaa4571c37.PNG)

Attached is a photo of what is happening, when swiping up the CC looks like that, but functions correctly. Issue remains after respeings and reboots.

**Comment by andrewwiik** [comment]
This is definitely a conflicting tweak, can I have a tweak list?

**Comment by Tom-Knighton** [comment]
Ah thank you I don't know why I didn't think of conflicting tweaks, the issue was with Minicc, disabled it and now it works perfectly thanks!
