### ISSUE TITLE
Ad Haptic feedback to Silent toggle 

### ISSUE THREAD

**Issue by maheshdj** [ioscreatix/Maize#28]
This would preventing accident on silent mode 
iPhone 6 ios 10.2

**Comment by andrewwiik** [comment]
Not understanding this

**Comment by maheshdj** [comment]
Ad Haptic feedback when toggle on this highlighted toggle

**Comment by maheshdj** [comment]
I send your mail for this checkout

**Comment by andrewwiik** [comment]
Does not align to how iOS 11 has it so closing the issue

**Comment by maheshdj** [comment]
Just want a vibration when Silent Mode Toggle
