### ISSUE TITLE
Ad auto Brightness toggle for reliability 

### ISSUE THREAD

**Issue by maheshdj** [ioscreatix/Maize#29]

**Comment by braedonrogers99** [comment]
This would be amazing

**Comment by andrewwiik** [comment]
Where would you suggest this be put and what do you mean by "reliability"?

**Comment by maheshdj** [comment]
Mean simplicity to get rid of every time go in setting for of auto
brightness

**Comment by Greg212** [comment]
Simplicity.. thanks, Johnny Ive 😁

**Comment by maheshdj** [comment]
Haha
