### ISSUE TITLE
Music Module crashes Maize on iOS 9

### ISSUE THREAD

**Issue by julianschiavo** [ioscreatix/Maize#33]
Hi,

Leaving this here so it can be fixed before Maize goes public - I **selfcompiled** a **private test** Maize for iOS 9, so please everyone, don't ask me for DEBs etc.

When enabling the MusicModule in com.ioscreatix.Maize.plist and rebooting, Maize crashes upon sliding up to open CC and Substrate enters safe mode.

Would be nice to see this fixed!

dotJS

**Comment by andrewwiik** [comment]
Their is newer issue on this with a discussion so I am closing this copy, even though this issue was filed first the other one has discussion attached so it is probably the better place for this issue to stay. Thank you for filing this bug.
