### ISSUE TITLE
Not seeing the whole CC

### ISSUE THREAD

**Issue by TheNightRider12** [ioscreatix/Maize#34]
I am only able to see about half of the CC. 
[Image Here](http://i.imgur.com/lmzuxjP.png)
Is this supposed to happen?

Tweak: 1.0.4. 
iPhone 6s 
iOS 10.1.1

**Comment by Greg212** [comment]
I'm not sure what you're referring to. This Maize Tweak is at the moment just a PREVIEW, like the filename in Cydia clearly says. Of course you are not able to use the full CC.
Greetings

**Comment by kaaslikker2** [comment]
The version from github is NOT the preview. just saying

**Comment by TheNightRider12** [comment]
I am not using the version from Github. I am using the one from the Cydia Repo

**Comment by kaaslikker2** [comment]
The one from Cydia is meant to be like that
