### ISSUE TITLE
Lag, Weird Names 

### ISSUE THREAD

**Issue by Dogman321** [ioscreatix/Maize#39]
iPhone 5s, 10.1.1

There is some lag with the control center and bugs with the pause and play button.
The controls such as Bluetooth, wifi, airplane mode is not showing correct names.
In settings, got some "FAILED_TO_LOAD_NAME" errors

So look out for those!

**Comment by andrewwiik** [comment]
I fixed the lag, what do you mean by the wrong names?

**Comment by Dogman321** [comment]
No need to worry, that issue was fixed

The Brightness slider is still a bit laggy but faster than it was before

**Comment by Dogman321** [comment]
The music both expanded and not, when the music is playing, the buttons would randomly switch from play to pause

**Comment by andrewwiik** [comment]
That is a seperate issue that someone has already filed so I will be marking this issue as closed for now
