### ISSUE TITLE
3D touch not working. 

### ISSUE THREAD

**Issue by hitesh1khandelwal** [ioscreatix/Maize#40]
As discussed on twitter earlier I have 3D touch off in the settings and then I try to long press it so that the menu pops up instead of popping up it just zooms a bit and nothing else happens. 

Device : iPhone 6s with broken 3D touch :(
iOS version: 10.2
Tested on Maize preview v1.1.2

**Comment by hitesh1khandelwal** [comment]
Sorry it's Maize Preview v1.1.1

**Comment by andrewwiik** [comment]
Will be looking into this today for you

**Comment by hitesh1khandelwal** [comment]
Thank you so much.

**Comment by andrewwiik** [comment]
I lied, I'm doing it right now instead

**Comment by andrewwiik** [comment]
I think I found the issue

**Comment by andrewwiik** [comment]
Pretty sure I fixed it for the next Maize preview

**Comment by hitesh1khandelwal** [comment]
Thank you so much :D
Finally I'd be able to use 3D touch in control panel :D
