### ISSUE TITLE
Part of cc disappears sometimes

### ISSUE THREAD

**Issue by MattIsAPerson** [ioscreatix/Maize#45]
https://imgur.com/gallery/ajWbO

Fixes after respring

**Comment by MattIsAPerson** [comment]
iPhone SE, 10.1.1

happens randomly

**Comment by andrewwiik** [comment]
It looks like you may have a conflicting tweak

**Comment by zyan910** [comment]
Wouldn't this make the CC faster cuz its removing most of the blur?

**Comment by andrewwiik** [comment]
Fixed
