### ISSUE TITLE
Laggy CC Animations

### ISSUE THREAD

**Issue by estebanGramajo** [ioscreatix/Maize#46]
You can notice with the rest of the animations that the pull-up part gets laggy always.

Here's a video of how it looks while on an app.
[IMG_1851.mp4.zip](https://github.com/ioscreatix/Maize/files/1337998/IMG_1851.mp4.zip)

And while on lockscreen. Here some stuff disapeared, like the long press menu on conectivity or the brightness of the flashlight.

[IMG_1852.mp4.zip](https://github.com/ioscreatix/Maize/files/1338005/IMG_1852.mp4.zip)

I'm on iPhone 6 - 10.2

**Comment by ann0see** [comment]
Can confirm on iPhone SE, but a reboot made it better.

**Comment by tomaszpoliszuk** [comment]
Please provide tweak list.

**Comment by estebanGramajo** [comment]
7-zip (POSIX): 4.57-3p
Activator: 1.9.13~beta1
Apple File Conduit "2": 1.2
AppList: 1.5.13
AppSync Unified: 6.0~b1
APT 0.6 Transitional: 1:0-23
APT 0.7 (apt-key): 0.7.25.3-3
APT 0.7 Strict (lib): 0.7.25.3-14
APT 0.7 Strict: 0.7.25.3-8
Base Structure: 1-4
BatteryLife: 1.7.0
Berkeley DB: 4.6.21-5
BetterTextSelection: 1.1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 4.0.44-16
BrowserChanger10: 1.1.1
BYA Repo Icons: 2.1.9
bzip2: 1.0.5-8
CallBar (iOS 10/9/8/7): 13-169
Cephei: 1.11
CleanNotifications10: 1.0.1-1
ColorBanners 2 (iOS 10): 1.0.2
Core Utilities (/bin): 8.12-9
Core Utilities: 8.12-1te
CoreXI (iOS 10): 1.2-1
CrackTool2: 2.3~beta9
Cream 2: 1.1-1
Creamy (iOS 10/9): 1.1
Curago: 0.2.4-0
Cydia Installer: 1.1.30
Cydia Substrate: 0.9.6301
Cydia Translations: 1.1.12
DarkMessages (iOS 10): 1.2.0-1
Darwin Tools: 1-5
Debian Packager: 1.18.10-12
Debian Utilities: 3.3.3ubuntu1-1p
Diff Utilities: 2.8.1-6
DismissMyKeyboard: 1.1-2
Ext3nder: 0.9.41_012
Filza File Manager: 3.3.2
Find Utilities: 4.2.33-7
Flame: 1.3
Flex 3: 3~EarlyAccess3
Flipswitch: 1.0.16~beta1
GNU Privacy Guard: 1.4.8-4
grep: 2.5.4-3
gzip: 1.6-7
HotDog: 3.3.3-1085+debug
iCleaner Pro: 7.6.2
IconBundles: 0.2-1
IconSupport: 1.10.0.2-1
InfoStats: 1.1.5
IOKit Tools: 76-4p
iOS Firmware: 10.2
iPhone Firmware (/sbin): 0-1
KarenLocalizer: 1.0.2
KarenPrefs: 1.1
libcolorpicker: 1.6-1
libpackageinfo: 1.1.0.1-1
libstatusbar: 1:0.9.9.0-1
Link Identity Editor: 1:1.2.1
LocationFaker(8,9,10): 2.0
LockGlyph (iOS 8-10): 1.2-beta6-1
LockHTML4: 1.3~beta2-1
LockScreenGestureCleanUp: 0.5-1
LS Barebones - Tiny Mod: 1.7
LS Barebones Nano: 1.1
LS Barebones: 1.10
Lylac: 1.0.10
LZMA Utils: 4.32.7-5
Maize (Preview): 1.1.2
mikoto: 3.0.8
Mitsuha: 0.9.1-1
NetworkList: 0.4.1
New Curses: 5.7-15
Noctis: 1.9.5.1-1+debug
NoSlowAnimations: 5.2.1
NudeKeys: 3.1
Opener: 3.1.2
PalBreak: 1.1
Palert: 1.1.0-2
PAM (Apple): 32.1-4
PAM Modules: 36.1-5
Patcyh: 1.2.0
pincrush: 0.9.2-1
Poke Patch for Pokemon Go!: 1.0r-9
PokeGo++ 2.0 for Pokemon Go!: 2.0r-40
Polus Alternative Glyphs: 1.0
Polus Extra Apps Glyph Pack: 1.0
Polus: 2.2.1
Power Tap: 1.1.3-3
PreferenceLoader: 2.2.4~alpha1
Profile Directory: 0-2
readline: 6.0-8
Repo Icons: 1.0
RocketBootstrap: 1.0.5
sed: 4.1.5-8
shell-cmds: 118-7
Snap + LITE for Snapchat: 1.0r-3
Springtomize 4 (iOS 10): 3
Springy: 11
Squid: 1.0
Substrate Safe Mode: 0.9.6001
system-cmds: 433.8-14
Tape Archive: 1.29-10
TechSupport Framework: 1.5.0.1-1
TransparentDock: 1.1-1
trustDevAlert: 0.1-1
tsProtector 8+ (iOS 9 & 8): 1.2.0-20
uasharedtools: 2.1r-110
UAUnbox: 0.0.2-1
UIKit Tools: 1.1.12
Unify X: 1.0.0.0
unrar: 3.6.8-2p
unzip: 5.52-5p
Upscale: 0.3.0-3
Veexillum: 2.7
Vibrancy (iOS 10): 1.0.1
VideoPlayerXI (iOS 10): 1.0-2
Wethr: 1.2-1
WinterBoard: 0.9.3919
xCon for PokemonGo: 45-6
zip: 2.32-5p

Tried disabling all the ones that targets the cc and it works better.

**Comment by andrewwiik** [comment]
Fixed, problem was a new instance of Maize was getting created for every settings change
