### ISSUE TITLE
Wrong colors on CC

### ISSUE THREAD

**Issue by estebanGramajo** [ioscreatix/Maize#47]
When using on white bg it looks really weird. Also, you can see a little bit of black on the borders of the active icons. The sound/brightness icon should turn black when the white surpases them, right?

![img_1861](https://user-images.githubusercontent.com/14099858/30936626-b9bfd1d2-a391-11e7-8ff2-4218567e3069.PNG)

**Comment by andrewwiik** [comment]
Fixed already
