### ISSUE TITLE
Stutters, Black Borders, & Play & Pause (6s Plus 10.2)

### ISSUE THREAD

**Issue by aviairy** [ioscreatix/Maize#53]
- Terrible stutter/drop in frame rate when two or more rows of toggles are added

- Black borders around smaller square toggles when on white background

- Play & pause icon do not line up in order of touch (when you pause, the play icon dos not pop up, when you play, the pause icon will not show up) [ as you can see, the music is paused, but once you play, its as if the icons are reversed and do not represent the actual playing and pausing)
[IMG_6684.mp4.mov.zip](https://github.com/ioscreatix/Maize/files/1343481/IMG_6684.mp4.mov.zip)

**Comment by aviairy** [comment]
![img_6685](https://user-images.githubusercontent.com/32384446/31006350-5b5d95b8-a4ca-11e7-94b5-003a7f1a00a4.PNG)
Also added the image of the black outline on the ringer, rotation lock, and night shit toggles

**Comment by andrewwiik** [comment]
I need a separate issue filed for the play and pause bit I fixed the other two issues so I am closing this issue.
