### ISSUE TITLE
Can you make HomeKit module and move Night Shift to Brightness module ???

### ISSUE THREAD

**Issue by mkizzle2906** [ioscreatix/Maize#54]
Can you add these feature to Maize ?
- HomeKit module to have favourite homekit stuff like iOS 11
- Move NightShift toggle into Brightness module
- Move Maize settings into Control Center settings page like iOS 11
Thanks

**Comment by bionicl** [comment]
Actually, I'll also love too use HomeKit module, or if it's too hard to do, maybe old Home app module as a 2nd page.

**Comment by andrewwiik** [comment]
Half done, HomeKit Module will most likely come later after release as it seems to be more work then I first thought it would be :(
