### ISSUE TITLE
[Resubmit] Play & Pause out of sync

### ISSUE THREAD

**Issue by aviairy** [ioscreatix/Maize#56]
[IMG_6684.mp4.mov.zip](https://github.com/ioscreatix/Maize/files/1345964/IMG_6684.mp4.mov.zip)
[iphone 6s plus, 10.2]

Same issue, notice on the first tap, the music widget (module) does not respond. it responds on the second tap, and once tapped, it switches rapidly making the music and module out of sync.

So, when playing, it shows the "play" icon (to make it play, even though its already playing)
and when paused, it shows the "pause" icon to make it pause (even though its already paused)

unless its supposed to be like this, then disregard this post

**Comment by Quoll-io** [comment]
Fixed.
