### ISSUE TITLE
MediaModule crashes SpringBoard on iOS 9

### ISSUE THREAD

**Issue by julianschiavo** [ioscreatix/Maize#62]
The music/media module currently crashes springboard whenever its turned on on iOS 9. I've attached a crash log to the issue.
This happens whenever the MediaModule is enabled, and disabling all other tweaks with iCleanerPro doesn't change anything.
[crash.log](https://github.com/ioscreatix/Maize/files/1346396/crash.log)

Thanks,
dotJS

**Comment by Quoll-io** [comment]
Thanks, I think I know what is causing it now.

**Comment by julianschiavo** [comment]
Awesome! Hopefully it'll be fixed soon 😃

**Comment by zyan910** [comment]
ive been trying to use it on my iOS 9 iPod 5, always takes me to safe mode when I swipe up

**Comment by Quoll-io** [comment]
@zyan910 yes, I know what the issue is, i'm fairly sure it's because a method I use is only iOS 10 and above.

**Comment by zyan910** [comment]
Oh ok...

**Comment by Quoll-io** [comment]
Fixed

**Comment by zyan910** [comment]
Which update?

**Comment by Quoll-io** [comment]
My lastest commit

**Comment by zyan910** [comment]
Ah thx
