### ISSUE TITLE
Recorder

### ISSUE THREAD

**Issue by MrBlock5633** [ioscreatix/Maize#63]
The recording module disappeared after one respring and I can't get it back

**Comment by andrewwiik** [comment]
Try going into the settings for the tweak and dragging it back up

**Comment by hitesh1khandelwal** [comment]
I am also having the same issue. I have added it in the settings as well but still I am not able to see the recoring module in cc.

**Comment by andrewwiik** [comment]
This may be fixed now so I am closing this issue for now
