### ISSUE TITLE
Error when I tap and hold shortcut Caculator and Flashlight

### ISSUE THREAD

**Issue by vyspirit** [ioscreatix/Maize#64]
iPhone 6s | iOS 10.2
Link video: https://streamable.com/4f28i

**Comment by andrewwiik** [comment]
Hmmmmmm, tweak list please

**Comment by vyspirit** [comment]
BioProtect
ColorFlow 3
HideMeX
JailProtect
LowerInstall
Sonus
Tage

**Comment by andrewwiik** [comment]
Most Likely Fixed

**Comment by vyspirit** [comment]
I still encounter the same situation in the latest version (1.0.4)
Link video: https://streamable.com/qc3cb
