### ISSUE TITLE
Bluetooth "always searching"

### ISSUE THREAD

**Issue by zyan910** [ioscreatix/Maize#65]
Bluetooth toggle always says searching even though I'm connected to my Apple Watch
![img_1643](https://user-images.githubusercontent.com/31066253/31054116-af846286-a6bc-11e7-8995-a994479ae2aa.PNG)

**Comment by andrewwiik** [comment]
Device and iOS Version Please

**Comment by mactavish14** [comment]
I'm also having this issue. iPhone 7, 10.1.1

**Comment by zyan910** [comment]
iPhone 6, iOS 10.1.1

**Comment by kaaslikker2** [comment]
iPhone 6s+ iOS 10.2

**Comment by michyprima** [comment]
same here, iPhone 6s iOS 10.2

**Comment by zyan910** [comment]
Im assuming this is fixed :)
