### ISSUE TITLE
stdc++.6 not explicitly linked

### ISSUE THREAD

**Issue by michyprima** [ioscreatix/Maize#66]
You may want to consider adding
`MaizeUI_LDFLAGS += -lstdc++.6`
to MaizeUI's Makefile. This would fix the build on non osx hosts.

**Comment by andrewwiik** [comment]
I would like to look into this more before I make this change to this project as I have never encountered this problem before.

**Comment by michyprima** [comment]
I believe that's because you use a mac. theos on linux and windows does not automatically link stdc++.6, causing the build to fail. Take your time. I went back to building Maize on macOS as the official toolchain builds smaller (better optimized?) binaries.
