### ISSUE TITLE
Volume control shows the iOS volume pop up when using it.

### ISSUE THREAD

**Issue by estebanGramajo** [ioscreatix/Maize#68]
[IMG_1946.mp4.zip](https://github.com/ioscreatix/Maize/files/1349217/IMG_1946.mp4.zip)

(Sorry for the bad english, can't find how to explain this).
It only happens after a respring, the first time you open the cc. When you close and reopen it, it fixes.

**Comment by andrewwiik** [comment]
Fixed I believe
