### ISSUE TITLE
Sometimes the cc is like this......

### ISSUE THREAD

**Issue by seang60** [ioscreatix/Maize#73]
![img_6856](https://user-images.githubusercontent.com/31991902/31308845-83ee5970-aba7-11e7-933d-6f33113a0e64.PNG)

**Comment by andrewwiik** [comment]
was able to reproduce, not sure what causes it in the code yet though

**Comment by estebanGramajo** [comment]
This happens to me a lot also, especially on landscape mode. When this happens, the only working area of the cc is the blured part. It only fixes with a respring.

**Comment by andrewwiik** [comment]
Fixed by latest commit
