### ISSUE TITLE
Springboard crashes when enabling the Flashlight

### ISSUE THREAD

**Issue by 0j0k3r** [ioscreatix/Maize#74]
When I try to enable my flashlight in Maize, my phone did a respring. I did not have MiniCC,Polus, or HorseShoe installed, and tried to disable all other of my tweaks with iCleaner, but that didnt help. I have a crashlog attached ;)

[SpringBoard-2017-10-07-171722.symbolicated.zip](https://github.com/ioscreatix/Maize/files/1365305/SpringBoard-2017-10-07-171722.symbolicated.zip)

**Comment by andrewwiik** [comment]
I think I know the problem but maybe not, I'll try adding a fix in the next version of the Maize Preview and you can let me know if it fixed the problem

**Comment by 0j0k3r** [comment]
…yea, lets hope that this fix will working 😉 

Von meinem iPhone gesendet

**Comment by andrewwiik** [comment]
Finally Fixed
