### ISSUE TITLE
RoundScreenCorners turning normal while opening CC

### ISSUE THREAD

**Issue by zyan910** [ioscreatix/Maize#76]
I have RoundScreenCorners installed but when I try open the control center, the corners become squared as normal. (Also Note that this only happens when I open it in the LS or HOME SCREEN
[IMG_1694.zip](https://github.com/ioscreatix/Maize/files/1369379/IMG_1694.zip)

**Comment by andrewwiik** [comment]
In this situation it is my professional opinion that RoundScreenCorners needs to support Maize and not the other way around, please contact the developer of RoundScreenCorners and ask her/him to add support for Maize

**Comment by zyan910** [comment]
Oh, ok
