### ISSUE TITLE
Maize occasionally causes the wifi signal strength icon to not appear in statusbar

### ISSUE THREAD

**Issue by michyprima** [ioscreatix/Maize#77]
When connecting to a wifi network, Maize causes the 4G icon to not turn into the wifi signal strength icon. I can verify I'm succesfully connected in settings and safari can browse via wifi. Reconnecting to wifi does not fix the issue; a respring does for a while but the issue eventually comes back.
I went back to horseshoe and I can confirm this does not happen anymore.

iPhone 6S, iOS 10.2

**Comment by hitesh1khandelwal** [comment]
This is happening to me as well but I didn't knew it is happening because of maize.

**Comment by zyan910** [comment]
Happens to me as well, its kind of annoying :(

**Comment by andrewwiik** [comment]
FIXED
