### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by ghost** [ioscreatix/Maize#8]
Hello

**Comment by andrewwiik** [comment]
If you can't build the project on your own you probably shouldn't be building it, this repository serves as a code base for developers who want to see how something is done, not for people to just compile and install as it could lead to your device being unable to boot into a jailbroken state of code is messed up.

**Comment by rubixRu** [comment]
is there any repo which has proper wiki to show the build process of such jailbroken projects.?
Regards
