### ISSUE TITLE
Screen recording button is not working

### ISSUE THREAD

**Issue by CrazzySwimmer** [ioscreatix/Maize#88]
I can´t get the screen recording feature to work. I have resprung many times and tried to change the positionoing of the icon in the settings but nothing is working

**Comment by andrewwiik** [comment]
Please explain what "not working" means, also your device and iOS Version

**Comment by CrazzySwimmer** [comment]
Sorry for my late response,

Im on an iPhone 6 ios 10.2
So i cant seem to get the screen recording toggle to work it just wont appear in the cc

**Comment by andrewwiik** [comment]
May have been fixed in my latest build, you'll have to wait for the final release now as I am done releasing previews
