### ISSUE TITLE
Additional toggles do not show up after adding

### ISSUE THREAD

**Issue by SilentOcean2017** [ioscreatix/Maize#89]
As the title said, when I add some more toggles, they don't appear. I tried reinstalling Maize but no luck. Please take a look at this, thank you guys so much.

**Comment by andrewwiik** [comment]
Device and iOS Version?

**Comment by SilentOcean2017** [comment]
Iphone 7, ios 10.1
I read a comment on reddit telling me to reboot, my phone, then rejailbreak and reinstall Maize. That well fixed this problem.
