### ISSUE TITLE
So I tried to remove lag in Maize by Reducing motion and Reducing Transparency and this happened

### ISSUE THREAD

**Issue by zyan910** [ioscreatix/Maize#95]
I was successful at removing the lag and Maize would work at 60 FPS! But this happened ![img_1903](https://user-images.githubusercontent.com/31066253/32134702-f6c053a6-bc03-11e7-89ae-5ff21762ebb8.PNG)

**Comment by andrewwiik** [comment]
This actually would be the proper behavior for how Maize should look when you do this so I am closing this issue
